#include "cli.h"
#include "doctest.h"
#include "file.h"
#include "hash.h"
#include "runner.h"
#include "test_utils.hpp"
#include <chrono>
#include <cstdio>
#include <fstream>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

static void write_file(const std::string &path, const std::string &content)
{
    std::ofstream ofs(path, std::ios::binary);
    ofs.write(content.data(), content.size());
}

TEST_CASE("E2E: Realistic SFV archive verification")
{
    // Create multiple realistic files
    write_file("e2e_sfv_1.bin", "Quick brown fox jumps over the lazy dog");
    write_file("e2e_sfv_2.bin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit");
    write_file("e2e_sfv_3.bin", "Pthread double-buffered pipelined verification test");

    std::string crc1 = hash_string(hashmonke_md_crc32(), "Quick brown fox jumps over the lazy dog");
    std::string crc2 = hash_string(hashmonke_md_crc32(), "Lorem ipsum dolor sit amet, consectetur adipiscing elit");
    std::string crc3 = hash_string(hashmonke_md_crc32(), "Pthread double-buffered pipelined verification test");

    std::string sfv_manifest =
        "; Generated by Hashmonke Test Suite\n"
        ";\n"
        "e2e_sfv_1.bin " + crc1 + "\n"
        "e2e_sfv_2.bin " + crc2 + "\n"
        "e2e_sfv_3.bin " + crc3 + "\n";

    write_file("e2e_archive.sfv", sfv_manifest);

    struct hashmonke_file *manifest = hashmonke_file_init(nullptr, "e2e_archive.sfv", HASHMONKE_FILE_FORMAT_AUTODETECT);
    REQUIRE(manifest != nullptr);
    CHECK_EQ(hashmonke_file_get_format(manifest), HASHMONKE_FILE_FORMAT_SFV);

    struct hashmonke_runner *runner = hashmonke_runner_run(manifest, [](const char *path, enum hashmonke_hash_code code) {
        (void)path;
        CHECK_EQ(code, HASHMONKE_HASH_MATCHES);
    });
    REQUIRE(runner != nullptr);

    hashmonke_runner_wait(runner);

    struct hashmonke_runner_stats stats = hashmonke_runner_get_stats(runner);
    CHECK(stats.is_finished);
    CHECK_EQ(stats.files_matched, 3u);
    CHECK_EQ(stats.files_failed, 0u);
    CHECK_EQ(stats.files_missing, 0u);
    CHECK_EQ(stats.files_malformed, 0u);
    CHECK_EQ(stats.total_files_processed, 3u);

    hashmonke_runner_free(runner);
    hashmonke_file_free(manifest);

    std::remove("e2e_sfv_1.bin");
    std::remove("e2e_sfv_2.bin");
    std::remove("e2e_sfv_3.bin");
    std::remove("e2e_archive.sfv");
}

TEST_CASE("E2E: Realistic GNU MD5 archive with mixed status")
{
    write_file("e2e_md5_ok.bin", "matching content");
    write_file("e2e_md5_bad.bin", "corrupted content");
    // e2e_md5_missing.bin not created!

    std::string md5_ok = hash_string(hashmonke_md_md5(), "matching content");
    std::string md5_bad_expected = hash_string(hashmonke_md_md5(), "expected content");

    std::string md5_manifest =
        "# GNU MD5 Checksums\n"
        + md5_ok + "  e2e_md5_ok.bin\n"
        + md5_bad_expected + " *e2e_md5_bad.bin\n"
        + "0123456789abcdef0123456789abcdef  e2e_md5_missing.bin\n"
        + "invalid record line here\n";

    write_file("e2e_checksums.md5", md5_manifest);

    struct hashmonke_file *manifest = hashmonke_file_init(nullptr, "e2e_checksums.md5", HASHMONKE_FILE_FORMAT_AUTODETECT);
    REQUIRE(manifest != nullptr);
    CHECK_EQ(hashmonke_file_get_format(manifest), HASHMONKE_FILE_FORMAT_GNU_MD5);

    struct hashmonke_runner *runner = hashmonke_runner_run(manifest, nullptr);
    REQUIRE(runner != nullptr);

    hashmonke_runner_wait(runner);

    struct hashmonke_runner_stats stats = hashmonke_runner_get_stats(runner);
    CHECK(stats.is_finished);
    CHECK_EQ(stats.files_matched, 1u);
    CHECK_EQ(stats.files_failed, 1u);
    CHECK_EQ(stats.files_missing, 1u);
    CHECK_EQ(stats.files_malformed, 1u);
    CHECK_EQ(stats.total_files_processed, 4u);

    hashmonke_runner_free(runner);
    hashmonke_file_free(manifest);

    std::remove("e2e_md5_ok.bin");
    std::remove("e2e_md5_bad.bin");
    std::remove("e2e_checksums.md5");
}

